sudo: false
addons:
  apt:
    packages:
      - slapd
language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install coverage coveralls
script:
  - coverage run --source indicium --omit='indicium/ldap/test.py' setup.py test
  - coverage report -m
after_success: coveralls
